version: "3"
services:
    frontend:
        container_name: frontend
        build:
            context: ./Frontend
            dockerfile: Dockerfile
        image: scocarojas/reactjs
        ports:
            - "4001:3000"
        volumes:
            - ./Frontend:/usr/src/app
    backend:
        container_name: backend
        build:  
            context: ./Backend
            dockerfile: Dockerfile
        image: socarojas/nodejs
        ports:
            - "4000:3000"
        volumes:
            - ./Backend:/usr/src/app
